### ISSUE TITLE
formio/angular-app-starterkit - Failed to compile.

### ISSUE THREAD

**Issue by dave-k** [formio/angular-app-starterkit#22]
formio/angular-app-starterkit - Failed to compile.

ng serve

````
ERROR in node_modules/angular-formio/grid/GridHeaderComponent.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-formio/grid/form/FormGridHeader.component.d.ts(6,9): error TS1086: An accessor cannot be declared in an ambient context.
````

package.json
````
{
  "name": "angular-app-starterkit",
  "version": "1.8.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "deploy": "ng build --prod --base-href /angular-app-starterkit/; cd dist; git init; git remote add origin git@github.com:formio/angular-app-starterkit.git; git checkout -b gh-pages; git add -A; git commit -m 'Update demo application'; git push -f origin gh-pages;"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.14",
    "@angular/common": "^7.2.14",
    "@angular/compiler": "^7.2.14",
    "@angular/core": "^7.2.14",
    "@angular/elements": "^7.2.14",
    "@angular/forms": "^7.2.14",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^7.2.14",
    "@angular/platform-browser-dynamic": "^7.2.14",
    "@angular/router": "^7.2.14",
    "angular-formio": "^4.4.3",
    "bootstrap": "^4.4.1",
    "bootswatch": "^4.4.1",
    "core-js": "^2.6.0",
    "font-awesome": "^4.7.0",
    "formiojs": "^4.8.0-rc.12",
    "lodash": "^4.17.15",
    "node-sass": "^4.13.0",
    "rxjs": "^6.5.4",
    "zone.js": "^0.10.2"
  },
  "browser": {
    "vm": false
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "^7.2.14",
    "@angular/language-service": "^7.2.14",
    "@types/jasmine": "^3.5.0",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^10.12.12",
    "codelyzer": "^4.5.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^3.1.3",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "protractor": "^5.4.2",
    "ts-node": "^7.0.1",
    "tslint": "^5.20.1",
    "typescript": "<3.2.0"
  }
}

````

**Comment by travist** [comment]
I think this is an Angular version issue. We still have not had a chance to upgrade everything to the latest Angular version.

**Comment by dave-k** [comment]
I did upgrade the app to Angular 10.
console output and package.json below 

console output:
````
$ ng serve
Warning: Entry point 'angular-formio' contains deep imports into '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'formio-manager' contains deep imports into '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'formio-grid' contains deep imports into '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'formio-resource' contains deep imports into '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

chunk {main} main.js, main.js.map (main) 51.9 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 631 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 9.32 MB [initial] [rendered]
Date: 2020-08-12T04:28:18.549Z - Hash: 0d42d6f13514f11eb0d3 - Time: 21681ms

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.regexp.exec'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/angular-formio/__ivy_ngcc__/core.js depends on 'formiojs'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/angular-formio/manager/form-manager.service.js depends on 'lodash/intersection'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/angular-formio/__ivy_ngcc__/custom-component/create-custom-component.js depends on 'lodash'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/angular-formio/__ivy_ngcc__/FormioBaseComponent.js depends on 'formiojs/utils/Evaluator'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/angular-formio/__ivy_ngcc__/resource/resource.service.js depends on 'native-promise-only'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/web.dom-collections.iterator'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.string.replace'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.string.iterator'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.regexp.to-string'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/angular-formio/manager/form-manager.service.js depends on 'lodash/each'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.reflect.construct'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.object.to-string'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.function.name'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.array.slice'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.array.iterator'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.array.from'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.array.concat'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.symbol.iterator'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/node_modules/formiojs/utils/Evaluator.js depends on 'core-js/modules/es.symbol.description'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./src/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/dkennedy/project-3/formio-angular7/node_modules/font-awesome/scss/_path.scss:6:2: Can't resolve '../node_modules/font-awesome/node_modules/font-awesome/fonts/fontawesome-webfont.eot' in '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/src'

  4 | @font-face {
  5 |   font-family: 'FontAwesome';
> 6 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
    |  ^
  7 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?#iefix&v=#{$fa-version}') format('embedded-opentype'),
  8 |     url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'),


ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./src/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/dkennedy/project-3/formio-angular7/node_modules/font-awesome/scss/_path.scss:7:2: Can't resolve '../node_modules/font-awesome/node_modules/font-awesome/fonts/fontawesome-webfont.eot' in '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/src'

  5 |   font-family: 'FontAwesome';
  6 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
> 7 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?#iefix&v=#{$fa-version}') format('embedded-opentype'),
    |  ^
  8 |     url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'),
  9 |     url('#{$fa-font-path}/fontawesome-webfont.woff?v=#{$fa-version}') format('woff'),


ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./src/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/dkennedy/project-3/formio-angular7/node_modules/font-awesome/scss/_path.scss:7:2: Can't resolve '../node_modules/font-awesome/node_modules/font-awesome/fonts/fontawesome-webfont.svg' in '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/src'

  5 |   font-family: 'FontAwesome';
  6 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
> 7 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?#iefix&v=#{$fa-version}') format('embedded-opentype'),
    |  ^
  8 |     url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'),
  9 |     url('#{$fa-font-path}/fontawesome-webfont.woff?v=#{$fa-version}') format('woff'),


ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./src/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/dkennedy/project-3/formio-angular7/node_modules/font-awesome/scss/_path.scss:7:2: Can't resolve '../node_modules/font-awesome/node_modules/font-awesome/fonts/fontawesome-webfont.ttf' in '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/src'

  5 |   font-family: 'FontAwesome';
  6 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
> 7 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?#iefix&v=#{$fa-version}') format('embedded-opentype'),
    |  ^
  8 |     url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'),
  9 |     url('#{$fa-font-path}/fontawesome-webfont.woff?v=#{$fa-version}') format('woff'),


ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./src/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/dkennedy/project-3/formio-angular7/node_modules/font-awesome/scss/_path.scss:7:2: Can't resolve '../node_modules/font-awesome/node_modules/font-awesome/fonts/fontawesome-webfont.woff' in '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/src'

  5 |   font-family: 'FontAwesome';
  6 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
> 7 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?#iefix&v=#{$fa-version}') format('embedded-opentype'),
    |  ^
  8 |     url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'),
  9 |     url('#{$fa-font-path}/fontawesome-webfont.woff?v=#{$fa-version}') format('woff'),


ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./src/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/dkennedy/project-3/formio-angular7/node_modules/font-awesome/scss/_path.scss:7:2: Can't resolve '../node_modules/font-awesome/node_modules/font-awesome/fonts/fontawesome-webfont.woff2' in '/Users/dkennedy/project-3/formio-angular7/angular-app-starterkit/src'

  5 |   font-family: 'FontAwesome';
  6 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
> 7 |   src: url('#{$fa-font-path}/fontawesome-webfont.eot?#iefix&v=#{$fa-version}') format('embedded-opentype'),
    |  ^
  8 |     url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'),
  9 |     url('#{$fa-font-path}/fontawesome-webfont.woff?v=#{$fa-version}') format('woff'),

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
````

package.json
````
{
  "name": "angular-app-starterkit",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "deploy": "ng build --prod --base-href /angular-app-starterkit/; cd dist; git init; git remote add origin git@github.com:formio/angular-app-starterkit.git; git checkout -b gh-pages; git add -A; git commit -m 'Update demo application'; git push -f origin gh-pages;"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.6",
    "@angular/common": "~10.0.6",
    "@angular/compiler": "~10.0.6",
    "@angular/core": "~10.0.6",
    "@angular/elements": "^10.0.8",
    "@angular/forms": "~10.0.6",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "~10.0.6",
    "@angular/platform-browser-dynamic": "~10.0.6",
    "@angular/router": "~10.0.6",
    "angular-formio": "^4.4.3",
    "bootstrap": "^4.4.1",
    "bootswatch": "^4.4.1",
    "core-js": "^3.6.5",
    "font-awesome": "^4.7.0",
    "formiojs": "^4.8.0-rc.12",
    "lodash": "^4.17.19",
    "node-sass": "^4.14.1",
    "rxjs": "~6.6.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.5",
    "@angular/cli": "~10.0.5",
    "@angular/compiler-cli": "~10.0.6",
    "@angular/language-service": "^10.0.8",
    "@types/node": "^14.0.27",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}

````

**Comment by travist** [comment]
I do not believe angular-formio is compatible with Angular 10 yet. We have that as a high priority to get to but currently other items have been deemed more critical.

**Comment by spraveenkar92** [comment]
After changing the version of "@angular-devkit/build-angular": from "^0.11.2", to "^0.803.21", got below issue,
https://github.com/formio/angular-app-starterkit/commit/0db3ed24759a65118538b5cf68aed99d577a6296


Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber.project (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\workspace\workspace.js:215:42)
    at MergeMapSubscriber._tryNext (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MapSubscriber._next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:86:26)
    at InnerSubscriber._next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:86:26)
    at InnerSubscriber._next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (D:\NewFolder\Studies\Formio\Office\Frontend\maybank-app-inventory-maybank-ad-login\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-app-starterkit@1.8.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-app-starterkit@1.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Praveenkumar\AppData\Roaming\npm-cache\_logs\2021-12-06T08_22_31_691Z-debug.log


After doing this change, it worked,
	"@angular-devkit/build-angular": "~0.7.0"
	pollyfills.ts - import 'core-js/es7/reflect';
